website/views.py
from flask import Blueprint, render_template, session, request, redirect, url_for
from .auth import login_required
import requests
from datetime import date, datetime
import calendar
import pandas as pd
import json
from .models import TemporaryPartidas, db

views = Blueprint('views', __name__)

@views.route('/', methods=['GET'])
@login_required
def home():
    authenticated = session.get('logged_in')
    email = session.get('identifier')
    
    # Fetch the data from TemporaryPartidas table for the user's email
    data = TemporaryPartidas.query.filter_by(email=email).order_by(TemporaryPartidas.Data.desc()).all()

    # Create a list of dictionaries from the fetched data
    data_list = []
    for row in data:
        data_dict = {
            'Partida': row.Partida,
            'Mapa': row.Mapa,
            'Kills': row.Kills,
            'Assists': row.Assists,
            'Mortes': row.Mortes,
            'Data': row.Data,
            'Score': f"{row.score_ally}:{row.score_enemy}",
            'Vitória': row.vitória,
            'PontosVar': row.PontosVar,
            'Pontos': row.Pontos,
        }
        data_list.append(data_dict)

    return render_template("home.html", authenticated=authenticated, data=data_list)

@views.route('/retrieve-data', methods=['POST'])
@login_required
def retrieve_data():
    if request.method == 'POST':
        cookies = session.get('cookies')
        headers = session.get('headers')
        email = session.get('identifier')

        TemporaryPartidas.query.filter_by(email=email).delete()
        db.session.commit()

        start_date = date(2023, 1, 1)
        today = date.today()
        current_year = today.year
        current_month = today.month

        url_template = 'https://gamersclub.com.br/players/get_playerLobbyResults/{}-{:02}/{}'

        # Fetch results and store them in TemporaryPartidas table
        for year in range(start_date.year, current_year + 1):
            start_month = 1 if year == start_date.year else 1
            end_month = current_month if year == current_year else 12

            for month in range(start_month, end_month + 1):
                month_end = calendar.monthrange(year, month)[1]
                url = url_template.format(year, month, 1)
                r = requests.get(url, cookies=cookies, headers=headers)
                json_data = r.json()
                total_pages = int(json_data['pagination']['pages_total'])
                print(f"Processing data for {year}-{month:02}, total pages: {total_pages}")

                for page in range(1, total_pages + 1):
                    url = url_template.format(year, month, page)
                    r = requests.get(url, cookies=cookies, headers=headers)
                    json_data = r.json()

                    for item in json_data['lista']:
                        room_a_vitoria = item['room_a_vitoria']
                        room_a_player = item['room_a_player']
                        score_ally = item['score_a'] if room_a_player else item['score_b']
                        score_enemy = item['score_b'] if room_a_player else item['score_a']
                        if (room_a_player and room_a_vitoria) or (not room_a_player and not room_a_vitoria):
                            vitória = 1
                        else:
                            vitória = 0
                        
                        
                        partida = TemporaryPartidas(
                            Partida=item['idlobby_game'],
                            Mapa=item['map_name'],
                            Kills=item['nb_kill'],
                            Assists=item['assist'],
                            Mortes=item['death'],
                            Data=datetime.strptime(item['created_at'], "%d/%m/%Y %H:%M"),
                            PontosVar=item['diference'],
                            Pontos=item['rating_final'],
                            vitória=vitória,
                            score_ally=score_ally,
                            score_enemy=score_enemy,
                            email=email
                        )
                        db.session.add(partida)

        db.session.commit()

    return redirect(url_for('views.home'))

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="graphs" href="/graphs">Graphs</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
    {% for category, message in messages %} 
    {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container-fluid">
      {% block contenttitle %}{% endblock %}
      {% block contentsubtitle %}{% endblock %}
      {% block content %}{% endblock %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.3.0/chart.min.js" integrity="sha512-mlz/Fs1VtBou2TrUkGzX4VoGvybkD9nkeXWJm3rle0DPHssYYx4j+8kIS15T78ttGfmOjH0lLaBXGcShaVkdkg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
{% block javascript %}
{% endblock %}
  </body>
</html>

website/templates/graphs.html
{% extends "base.html" %}

{% block title %}GamersClub Stats{% endblock %}
{% block contentsubtitle %}
  <div style="margin-left: 15px;">
    <h1>GamersClub Stats</h1>
    <p>Bem-vindo a GamersClub Stats, para carregar xo.</p>
    <div style="height: 20px;"></div>
  </div>
{% endblock %}

{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js"
    integrity="sha512-VCHVc5miKoln972iJPvkQrUYYq7XpxXzvqNfiul1H4aZDwGBGC0lq373KNleaB2LpnC2a/iNfE5zoRYmB4TRDQ==" 
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    
    <script>
        var ctx = document.getElementById('vitoriaspormes').getContext('2d');
    
        // Create a list with the count of matches for each month
        var vitoriaCountData = {{ vitoria_count_by_month | safe }};
        var derrotaCountData = {{ derrota_count_by_month | safe }};
        var monthsLabels = {{ months | safe }};
    
        var barChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: monthsLabels,
                datasets: [
                    {
                        label: 'Vitórias',
                        data: vitoriaCountData,
                        backgroundColor: 'rgba(90, 211, 52, 0.8)',
                        borderColor: 'rgba(53, 130, 29, 0.8)',
                        borderWidth: 0
                    },
                    {
                        label: 'Derrotas',
                        data: derrotaCountData,
                        backgroundColor: 'rgba(203, 44, 44, 0.8)',
                        borderColor: 'rgba(122, 12, 12, 0.8)',
                        borderWidth: 0
                    }
                ]
            },
            options: {
            plugins: {title:{display: true, text: 'Vitórias/ Derrotas por Mês', font: {size: 20} ,padding:{top: 0, bottom:10}}},
            maintainAspectRatio: false,
            scales: {
                y: {
                    beginAtZero: true,
                    stacked: true,
                    grid: {
                        display: true, // Remove vertical grey lines
                    },
                    ticks: {
                        stepSize: 10,
                    }
                },
                x: {
                    stacked: true,
                    grid: {
                        display: false, // Remove horizontal grid lines
                    }
                }
            }
        }
    });

    </script>
    

{% endblock %}

{% block content %}
<div class="col-xs-10 col-sm-6 col-md-6">
    <div class="card card-style mb-2">
        <div class="card-body">
            <div class="chart-container" style="position: relative;">
                <canvas id="vitoriaspormes" style="max-width: 900px; width: 100%;" height="400"></canvas>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}GamersClub Stats{% endblock %}
{% block contentsubtitle %}
  <div style="margin-left: 15px;">
    <h1>GamersClub Stats</h1>
    <p>Bem-vindo a GamersClub Stats, para carregar ou atualisar suas partidas, basta clicar no botão abaixo.</p>
    <form method="POST" action="{{ url_for('views.retrieve_data') }}">
        <div class="d-flex">
            <button type="submit" class="btn btn-primary">Atualizar Partidas</button>
        </div>
    </form>
    <div style="height: 20px;"></div>
  </div>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-lg-10">
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>Partida</th>
                            <th>Mapa</th>
                            <th>Kills</th>
                            <th>Assists</th>
                            <th>Mortes</th>
                            <th>Data</th>
                            <th>Score</th>
                            <th>Vitória/Derrota</th>
                            <th>PontosVar</th>
                            <th>Pontos</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for row in data %}
                            <tr>
                                <td>{{ row.Partida }}</td>
                                <td>{{ row.Mapa }}</td>
                                <td>{{ row.Kills }}</td>
                                <td>{{ row.Assists }}</td>
                                <td>{{ row.Mortes }}</td>
                                <td>{{ row.Data }}</td>
                                <td>{{ row.Score }}</td>
                                <td>{{ row.Vitória }}</td>
                                <td>{{ row.PontosVar }}</td>
                                <td>{{ row.Pontos }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}GamersClub Stats{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 align="center">Iniciar Sessão</h3>
      <div class="form-group">
        <label for="identifier">E-mail</label>
        <input
          type="identifier"
          class="form-control"
          id="identifier"
          name="identifier"
          placeholder="Seu email da GamersClub ID"
        />
      </div>
      <div class="form-group">
        <label for="password">Senha</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Sua senha"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Entrar</button>
    </form>
    {% endblock %}